<?php

namespace ContainerNvJc2xI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oQeH6FZ.App\Entity\Compte' shared service.
     *
     * @return \App\Entity\Compte
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oQeH6FZ": it references class "App\\Entity\\Compte" but no such service exists.');
    }
}
