<?php

namespace ContainerNvJc2xI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaissierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5789TdV.App\Entity\Caissier' shared service.
     *
     * @return \App\Entity\Caissier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5789TdV": it references class "App\\Entity\\Caissier" but no such service exists.');
    }
}
