<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIQ1V5Fh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIQ1V5Fh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIQ1V5Fh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIQ1V5Fh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIQ1V5Fh\App_KernelDevDebugContainer([
    'container.build_hash' => 'IQ1V5Fh',
    'container.build_id' => '27e0e49b',
    'container.build_time' => 1616464939,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIQ1V5Fh');
