<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5dC3ySU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5dC3ySU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5dC3ySU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5dC3ySU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5dC3ySU\App_KernelDevDebugContainer([
    'container.build_hash' => '5dC3ySU',
    'container.build_id' => '32645f6b',
    'container.build_time' => 1614368426,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5dC3ySU');
