<?php

namespace ContainerIQ1V5Fh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OxOyE3eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oxOyE3e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oxOyE3e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', '.errored..service_locator.oxOyE3e.Doctrine\\Persistence\\ObjectManager', NULL, 'Cannot autowire service ".service_locator.oxOyE3e": it references interface "Doctrine\\Persistence\\ObjectManager" but no such service exists. You should maybe alias this interface to the existing "doctrine.orm.default_entity_manager" service.'],
            'token' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'manager' => 'Doctrine\\Persistence\\ObjectManager',
            'token' => '?',
        ]);
    }
}
