<?php

namespace ContainerIQ1V5Fh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OQeH6FZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oQeH6FZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oQeH6FZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.oQeH6FZ.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.oQeH6FZ": it references class "App\\Entity\\Compte" but no such service exists.'],
        ], [
            'data' => 'App\\Entity\\Compte',
        ]);
    }
}
